name: build

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.lock') }}

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: dependencies-node-${{ hashFiles('package-lock.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite
          coverage: pcov

      - name: Create database
        run: touch database/database.sqlite

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress

      - name: Install NPM dependencies
        run: npm install --no-audit --no-optional

      - name: Compile assets
        run: npm run production

      - name: Execute tests
        run: |
          vendor/bin/phpcs
          vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
